Testing addUser shopper1 ... ok!    
Testing addUser shopper1 duplicate ... ok!
Adding all users  ... ok!
Testing login for all users ... ok!
Testing addCategory for a shopper ... ok!
Testing addCategory TSHIRT for admins ... ok!
Testing addCategory BOOK for admins ... ok!
Testing addDistributionCenter  ... ok!
Testing addCustomer for Shopper1 ... ok!
Testing addCustomer for duplicates: adding Shopper1 again ... ok!
Testing addCustomer  ... ok!
Testing addRoute for admin ... ok!
Testing addProduct for a shopper ... ok!
Test adding all products ... ok!
Testing prodInquiry prodID=9999 ... ok!
Testing prodInquiry non existent center X ... ok!
Testing updateQuantity for prodID=9999 ... ok!
Testing updateQuantity prodID=1 center X ... ok!
Testing update quantity, trying to add 100 units of prodID= 1 to warehouse A
Testing update quantity, trying to add 200 units of prodID= 1 to warehouse E
Testing update quantity, trying to add 300 units of prodID= 1 to warehouse I
Testing update quantity, trying to add 50 units of prodID= 2 to warehouse A
Testing update quantity, trying to add 50 units of prodID= 2 to warehouse E
Testing update quantity, trying to add 50 units of prodID= 2 to warehouse I
Testing update quantity, trying to add 300 units of prodID= 3 to warehouse A
Testing update quantity, trying to add 200 units of prodID= 3 to warehouse E
Testing update quantity, trying to add 100 units of prodID= 3 to warehouse I
Testing update quantity, trying to add 1000 units of prodID= 4 to warehouse A
Testing update quantity, trying to add 2000 units of prodID= 4 to warehouse E
Testing update quantity, trying to add 3000 units of prodID= 4 to warehouse I
Testing updateQuantity ... ok!
Testing prodInquiry prodID=1 warehouse A expected 100 ... got 100, ok!
[A, C, D, E, H, J]
[B, E, H, J]
[C, D, E, H, J]
[D, E, H, J]
[E, H, J]
[F, C, D, E, H, J]
[G, J]
[H, J]
[I, J]
null
{1200=[D, E, H, J], 800=[E, H, J], 2400=[F, C, D, E, H, J], 2100=[I, J], 1400=[C, D, E, H, J], 1800=[G, J], 200=[H, J], 2300=[A, C, D, E, H, J]}
[A, C, D, E, H, J]
[B, E, H, J]
[C, D, E, H, J]
[D, E, H, J]
[E, H, J]
[F, C, D, E, H, J]
[G, J]
[H, J]
[I, J]
null
{1200=[D, E, H, J], 800=[E, H, J], 2400=[F, C, D, E, H, J], 2100=[I, J], 1400=[C, D, E, H, J], 1800=[G, J], 200=[H, J], 2300=[A, C, D, E, H, J]}
Testing placeOrder, shopper=B, Prod=1, qty = 100 ...  ok!
-Testing placeOrder, shopper=B, Prod=1, qty = 100 ...  inventory balance 200, expected 100
Testing placeOrder, shopper=B, Prod=1, qty = 100 ...  shipping computed ok!
-Testing placeOrder, shopper=B, Prod=1, qty = 100 ...  route [H, J], expected [E,B]
[A, C, D, E, H, J]
[B, E, H, J]
[C, D, E, H, J]
[D, E, H, J]
[E, H, J]
[F, C, D, E, H, J]
[G, J]
[H, J]
[I, J]
null
{1200=[D, E, H, J], 800=[E, H, J], 2400=[F, C, D, E, H, J], 2100=[I, J], 1400=[C, D, E, H, J], 1800=[G, J], 200=[H, J], 2300=[A, C, D, E, H, J]}
-Testing placeOrder, shopper=B, Prod=4, qty = 4000 ...  orderID = 2, expected -1
Testing placeOrder, shopper=B, Prod=4, qty = 4000 ...  inventory balance ok!
-Testing placeOrder, shopper=J, Prod=3, qty = 195 ... orderID test failed, exception:
java.lang.NullPointerException
	at finalproject.Project.invoiceAmount(Project.java:452)
	at finalproject.ProjectTest.test3PlaceOrder(ProjectTest.java:713)
	at finalproject.ProjectTest.testAll(ProjectTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
-Testing placeOrder, shopper=J, Prod=3, qty = 195 ... inventory balance test failed, exception:
java.lang.NullPointerException
	at finalproject.Project.invoiceAmount(Project.java:452)
	at finalproject.ProjectTest.test3PlaceOrder(ProjectTest.java:713)
	at finalproject.ProjectTest.testAll(ProjectTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
-Testing placeOrder, shopper=J, Prod=3, qty = 195 ... invoice test failed, exception:
java.lang.NullPointerException
	at finalproject.Project.invoiceAmount(Project.java:452)
	at finalproject.ProjectTest.test3PlaceOrder(ProjectTest.java:713)
	at finalproject.ProjectTest.testAll(ProjectTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
-Testing placeOrder, shopper=J, Prod=3, qty = 195 ... route test failed, exception:
java.lang.NullPointerException
	at finalproject.Project.invoiceAmount(Project.java:452)
	at finalproject.ProjectTest.test3PlaceOrder(ProjectTest.java:713)
	at finalproject.ProjectTest.testAll(ProjectTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Testing placeOrder, user not logged in ...  ok!
Testing placeOrder, user admin ...   ok!
